config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'} 

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show' 

  resources :blogs

  root to: "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates_presence_of :title, :body
	belongs_to :topic 
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies, 
								  reject_if: lambda { |attrs| attrs['name'].blank? }

	include Placeholder
	validates_presence_of :title, :body, :main_image, :thumb_image

	def self.angular
		where(subtitle: "Angular")
	end

	scope :ruby_on_rails_portfolio_items, -> {where(subtitle: "Ruby on rails")}

	after_initialize :set_defaults
	def set_defaults
		self.main_image ||= Placeholder.image_generator(height:'600',width:'200')
		self.thumb_image ||= Placeholder.image_generator(height:'350',width:'200')
	end
end

app/models/skill.rb
class Skill < ApplicationRecord	
	include Placeholder
	validates_presence_of :title, :percent_utilized

	after_initialize :set_defaults
	def set_defaults
		self.badge ||= Placeholder.image_generator(height:'250',width:'250')
	end	
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title

	has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DefaultPageContent

  before_action :set_source

  def set_source
  	session[:source] = params[:q] if params[:q]
  end 

  before_action :set_title

  def set_title
  	@page_title = "ClassApp | CC"
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @page_title = "Blog Title"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
	extend ActiveSupport::Concern

	included do 
		before_action :set_page_defaults
	end

	def set_page_defaults
		@page_title = "ClassApp | CC"
		@seo_keywords = "my name"
	end
end

app/controllers/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern

	def self.image_generator(height:,width:)
		"http://via.placeholder.com/#{height}x#{width}"
	end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@posts = Blog.all
  	@skills = Skill.all 
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	layout "portfolio"
	
	def index
		@portfolio_items = Portfolio.all
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end

	def new
		@portfolio_item = Portfolio.new 
		3.times { @portfolio_item.technologies.build }
	end

	def create
	    @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

	    respond_to do |format|
	      if @portfolio_item.save
	        format.html { redirect_to portfolios_path, notice: 'Your portfolio was successfully created.' }
	      else
	        format.html { render :new }
	      end
	    end
	end

	def edit
		@portfolio_item = Portfolio.find(params[:id])
		3.times { @portfolio_item.technologies.build }
	end

	def update
		@portfolio_item = Portfolio.find(params[:id])

    	respond_to do |format|
      		if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        		format.html { redirect_to portfolios_path, notice: 'The record was successfully updated.' }
      		else
        		format.html { render :edit }
      		end
    	end
  	end

  	def show
		@portfolio_item = Portfolio.find(params[:id])
  	end

  	def destroy
		@portfolio_item = Portfolio.find(params[:id])

	    @portfolio_item.destroy

	    respond_to do |format|
	      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
  		end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login_helper
		if current_user 
			link_to "Logout", destroy_user_session_path, method: :delete 
	 	else 
	 		(link_to "Register", new_user_registration_path) + 
	 		"<br>".html_safe + 
	 		(link_to "Login", new_user_session_path)
		end 
	end

	def source_helper(layout_name)
		if session[:source]
			greeting = "Thank you for visiting from #{session[:source]} and you are in the #{layout_name} layout"
			content_tag(:p, greeting, class: "source-greeting")
		end
	end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<tr>
	<td><%= blog.title %></td>
	<td>Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</td>
	<td><%= blog.body %></td>
	<td><%= link_to 'Show', blog %></td>
	<td><%= link_to 'Edit', edit_blog_path(blog) %></td>
	<td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= render "shared/nav", location: 'top' %>

	<%= login_helper %>

	<%= yield %>

	<%= source_helper("application") %>

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= login_helper %>

	<%= yield %>

	<%= render "shared/nav", location: 'bottom' %>

	<%= source_helper("blog") %>

  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= render "shared/nav", location: 'top' %>

	<%= login_helper %>

	<%= yield %>

	<%= source_helper("porfolio") %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>

<p><%= number_to_phone "5555555555" %> </p>

app/views/pages/home.html.erb
<h1>Home page</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h2>Blog Posts</h2>
<%= @posts.inspect %>

<h2>Skills</h2>
<%= @skills.inspect %>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title%>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle%>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body%>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
	<%= link_to "edit", edit_portfolio_path(portfolio_item) %>
	<%= link_to "delete", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure"} %>

app/views/portfolios/angular.html.erb
<h1>Angular items</h1>

<%= link_to "create new item", new_portfolio_path %>

<% @angular_portfolio_items.each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
	<%= link_to "edit", edit_portfolio_path(portfolio_item) %>
	<%= link_to "delete", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure"} %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %> 

app/views/portfolios/index.html.erb
<h1>Portfolio items</h1>

<%= link_to "create new item", new_portfolio_path %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>create a new portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %> 

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<h2> Technologies used </h2>
<% @portfolio_item.technologies.each do |form| %>
<p><%= form.name %></p>
<% end %>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
	<div><%= link_to "Home", root_path %></div>
	<div><%= link_to "About me", about_me_path %></div>
	<div><%= link_to "Contact", contact_path %></div>
	<div><%= link_to "Blog", blogs_path %></div>
	<div><%= link_to "Portfolios", portfolios_path %></div>
</div>